service: ServiceName
provider:
  name: aws
  runtime: nodejs14.x
  stage: dev/production
  region: LAMBDA_REGION
  memorySize: 2048
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource: { "Fn::Join": ["", ["arn:aws:s3:::S3_BUCKET_NAME", "/*"]] }
plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-warmup
custom:
  warmup:
    default:
      enabled: true # Whether to warm up functions by default or not
      folderName: '.warmup' # Name of the folder created for the generated warmup 
      cleanFolder: false
      memorySize: 256
functions:
  app:
    handler: server.handler
    warmup:
      default:
        enabled: true
    timeout: 120
    events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true